api-version: 1.13
name: spacecraft
main: minecraft.SpaceCraft
version: 1.0
author: land00000
commands:
    setfreq:
       description: sets the frequency of event rolls.
       usage: /<command>
       permission: spacecraft.setfreq
       permission-message: You don't have <permission>
    showevents:
      description: sets the frequency of event rolls.
      usage: /<command>
      permission: spacecraft.showevents
      permission-message: You don't have <permission>
    addoxy:
      description: sets the probability of a spacecraft event.
      usage: /<command>
      permission: spacecraft.addoxy
      permission-message: You don't have <permission>
    updateprob:
      description: sets the probability of a spacecraft event.
      usage: /<command>
      permission: spacecraft.updateprob
      permission-message: You don't have <permission>
    updatefreq:
      description: sets the probability of a spacecraft event.
      usage: /<command>
      permission: spacecraft.updatefreq
      permission-message: You don't have <permission>