api-version: 1.13
name: spacecraft
main: minecraft.SpaceCraft
version: 1.0
author: land00000
commands:
    setfreq:
       description: sets the frequency of event rolls.
       usage: /<command>
       permission: spacecraft.setfreq
       permission-message: You don't have <permission>
    showevents:
      description: sets the frequency of event rolls.
      usage: /<command>
      permission: spacecraft.showevents
      permission-message: You don't have <permission>
    addoxy:
      description: sets the probability of a spacecraft event.
      usage: /<command>
      permission: spacecraft.addoxy
      permission-message: You don't have <permission>
    removeoxy:
      description: sets the probability of a spacecraft event.
      usage: /<command>
      permission: spacecraft.removeoxy
      permission-message: You don't have <permission>
    updateprob:
      description: sets the probability of a spacecraft event.
      usage: /<command>
      permission: spacecraft.updateprob
      permission-message: You don't have <permission>
    updatefreq:
      description: sets the probability of a spacecraft event.
      usage: /<command>
      permission: spacecraft.updatefreq
      permission-message: You don't have <permission>
    gravitystrength:
      description: sets the probability of a spacecraft event.
      usage: /<command>
      permission: spacecraft.gravitystrength
      permission-message: You don't have <permission>
    gravitymeter:
      description: sets the probability of a spacecraft event.
      usage: /<command>
      permission: spacecraft.gravitymeter
      permission-message: You don't have <permission>
    oxymeter:
      description: sets the probability of a spacecraft event.
      usage: /<command>
      permission: spacecraft.oxymeter
      permission-message: You don't have <permission>
    giveplayercompass:
      description: sets the probability of a spacecraft event.
      usage: /<command>
      permission: spacecraft.giveplayercompass
      permission-message: You don't have <permission>
    gravityoff:
      description: sets the probability of a spacecraft event.
      usage: /<command>
      permission: spacecraft.gravityoff
      permission-message: You don't have <permission>
    gravityon:
      description: sets the probability of a spacecraft event.
      usage: /<command>
      permission: spacecraft.gravityon
      permission-message: You don't have <permission>
    addcmd:
      description: sets the probability of a spacecraft event.
      usage: /<command>
      permission: spacecraft.addcmd
      permission-message: You don't have <permission>
    removecmd:
      description: sets the probability of a spacecraft event.
      usage: /<command>
      permission: spacecraft.removecmd
      permission-message: You don't have <permission>
    addwaypoint:
      description: sets the probability of a spacecraft event.
      usage: /<command>
      permission: spacecraft.addwaypoint
      permission-message: You don't have <permission>
    clearwaypoints:
      description: sets the probability of a spacecraft event.
      usage: /<command>
      permission: spacecraft.clearwaypoints
      permission-message: You don't have <permission>
    showwaypoints:
      description: sets the probability of a spacecraft event.
      usage: /<command>
      permission: spacecraft.removecmd
      permission-message: You don't have <permission>
    givesiphon:
      description: sets the probability of a spacecraft event.
      usage: /<command>
      permission: spacecraft.givesiphon
      permission-message: You don't have <permission>
